//Bien toan cuc
export default {
  jobName: {
    MINT_WORKER : 'MINT_WORKER',
    TRANFER_WORKER: 'TRANFER_WORKER',
    APPROVAL_WORKER: 'APPROVAL_WORKER',
    CLAIM_TOKEN_WORKER: 'CLAIM_TOKEN_WORKER',
    AUCTION_CREATED_WORKER: 'AUCTION_CREATED_WORKER',
    AUCTION_CANCELLED_WORKER: 'AUCTION_CANCELLED_WORKER'
  }
}
